### ISSUE TITLE
routingpy ipykernel update

### ISSUE THREAD

**Issue by ArterialMapping** [gis-ops/routing-py#66]
Is it possible to update routingpy per this documentation? https://github.com/giswqs/geospatial/issues/16

> @ArterialMapping It appears that `routingpy` requires `ipykernel >=5.3.4,<6`, which was released over a year ago. Many packages in the geospatial stack require a much newer version of ipykernel. `routingpy` needs to bring ipykernel up to date before it can be added to geospatial.
> 
> https://github.com/conda-forge/routingpy-feedstock/blob/c32ee1d1500c3f6bbda723b342886b9b45488513/recipe/meta.yaml#L30 ![image](https://user-images.githubusercontent.com/5016453/165417888-5b7a03fb-14e6-4cd4-a13c-217ebe59c9a8.png)
> 
> [![image](https://user-images.githubusercontent.com/5016453/165417350-01364ee8-8052-4807-8be2-4430bd20c045.png)

**Comment by nilsnolde** [comment]
problem is that we didn't even know that routingpy is on conda-forge. it's a separate repo, they didn't even tell us it exists or ask for upstream support, and now it's stale, because they didn't touch it in 1 year. either someone steps up and includes a direct conda-forge support in routingpy (this repo) or they'll be better following upstream releases or we'll remove routingpy entirely from conda. 

this is the repo, I already opened an issue, let's see what they say: https://github.com/conda-forge/routingpy-feedstock
